apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-customer-web-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-customer-web
  template:
    metadata:
      labels:
        app: store-customer-web
    spec:
      containers:
        - name: store-customer-web-container
          image: store-customer-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
