  apiVersion: v1
  kind: Pod
  metadata:
    name: store-customer-web-pod
    labels:
      app: store-customer-web
  spec:
    containers:
    - name: store-customer-web-container
      image: store-customer-web:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      env:
      - name: NODE_ENV
        value: "production"
