apiVersion: v1
kind: Service
metadata:
  name: store-customer-web-service
spec:
  selector:
    app: store-customer-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
